version: '3.7'

services:
  sonet_back:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
  sonet-db:
    image: postgres:14.6-alpine
    volumes:
      - sonet_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  pgadmin:
    image: chorss/docker-pgadmin4
    ports:
      - 5050:5050

volumes:
  sonet_postgres_data: